# platform :ios, '9.0'

target 'PragatiProject' do
  use_frameworks!
  pod 'Alamofire'
  pod 'GoogleMaps'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'iOSDropDown'
  pod 'SwiftHSVColorPicker'
  pod 'SwiftKeychainWrapper'

  # Pods for PragatiProject

  target 'PragatiProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PragatiProjectUITests' do
    # Pods for testing
  end

end
